In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [15]:
pip install pandas


SyntaxError: invalid syntax (Temp/ipykernel_1764/3082025228.py, line 1)

In [17]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.


In [16]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [5]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/siddiquiamir/Python-Books/master/houseprice.csv")
df.head()

OverallQual  OverallCond  BsmtFinSF1  GrLivArea  BedroomAbvGr  GarageArea  \
0            7            5         706       1710             3         548   
1            6            8         978       1262             3         460   
2            7            5         486       1786             3         608   
3            7            5         216       1717             3         642   
4            8            5         655       2198             4         836   

   SalePrice  
0     208500  
1     181500  
2     223500  
3     140000  
4     250000

In [6]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

data = pd.read_csv("https://raw.githubusercontent.com/siddiquiamir/Python-Books/master/houseprice.csv")
data.head()

OverallQual  OverallCond  BsmtFinSF1  GrLivArea  BedroomAbvGr  GarageArea  \
0            7            5         706       1710             3         548   
1            6            8         978       1262             3         460   
2            7            5         486       1786             3         608   
3            7            5         216       1717             3         642   
4            8            5         655       2198             4         836   

   SalePrice  
0     208500  
1     181500  
2     223500  
3     140000  
4     250000

In [7]:
data.isnull().sum()

OverallQual     0
OverallCond     0
BsmtFinSF1      0
GrLivArea       0
BedroomAbvGr    0
GarageArea      0
SalePrice       0
dtype: int64

In [18]:
data = data.dropna()


In [22]:
fig = px.scatter(data, x="GrLivArea", y="SalePrice",
                 size='GrLivArea')
fig.show()

NameError: name 'px' is not defined

In [21]:
print(data.corr())

              OverallQual  OverallCond  BsmtFinSF1  GrLivArea  BedroomAbvGr  \
OverallQual      1.000000    -0.090273    0.210969   0.624370      0.135751   
OverallCond     -0.090273     1.000000   -0.081763  -0.132050      0.008297   
BsmtFinSF1       0.210969    -0.081763    1.000000   0.166950     -0.089220   
GrLivArea        0.624370    -0.132050    0.166950   1.000000      0.511838   
BedroomAbvGr     0.135751     0.008297   -0.089220   0.511838      1.000000   
GarageArea       0.625118    -0.153564    0.289367   0.486134      0.068641   
SalePrice        0.809258    -0.111559    0.407437   0.755993      0.164898   

              GarageArea  SalePrice  
OverallQual     0.625118   0.809258  
OverallCond    -0.153564  -0.111559  
BsmtFinSF1      0.289367   0.407437  
GrLivArea       0.486134   0.755993  
BedroomAbvGr    0.068641   0.164898  
GarageArea      1.000000   0.684838  
SalePrice       0.684838   1.000000  


In [23]:
correlations = data.corr(method='pearson')
plt.figure(figsize=(13, 12))
sns.heatmap(correlations, cmap="coolwarm", annot=True)
plt.show()

In [24]:
x = data[["GrLivArea", "GarageArea"]]
y = data["SalePrice"]

In [25]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, 
                                                test_size=0.4, 
                                                random_state=40)
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(xtrain, ytrain)

DecisionTreeRegressor()

In [28]:
features = np.array([[140.00, 145.00]])
model.predict(features)

array([68500.])

In [29]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/siddiquiamir/Python-Books/master/houseprice.csv')

print(df.to_string()) 


     OverallQual  OverallCond  BsmtFinSF1  GrLivArea  BedroomAbvGr  GarageArea  SalePrice
0              7            5         706       1710             3         548     208500
1              6            8         978       1262             3         460     181500
2              7            5         486       1786             3         608     223500
3              7            5         216       1717             3         642     140000
4              8            5         655       2198             4         836     250000
5              5            5         732       1362             1         480     143000
6              8            5        1369       1694             3         636     307000
7              7            6         859       2090             3         484     200000
8              7            5           0       1774             2         468     129900
9              5            6         851       1077             2         205     118000
10        

In [30]:
import pandas as pd

print(pd.options.display.max_rows) 

60


In [37]:
import pandas as pd

df = pd.read_csv('.csv')

print(df) 

     OverallQual  OverallCond  BsmtFinSF1  GrLivArea  BedroomAbvGr  \
0              7            5         706       1710             3   
1              6            8         978       1262             3   
2              7            5         486       1786             3   
3              7            5         216       1717             3   
4              8            5         655       2198             4   
5              5            5         732       1362             1   
6              8            5        1369       1694             3   
7              7            6         859       2090             3   
8              7            5           0       1774             2   
9              5            6         851       1077             2   
10             5            5         906       1040             3   
11             9            5         998       2324             4   
12             5            6         737        912             2   
13             7    

In [38]:
import numpy as np
csv = np.genfromtxt('https://raw.githubusercontent.com/siddiquiamir/Python-Books/master/houseprice.csv', delimiter=",")
print(csv)

[[      nan       nan       nan ...       nan       nan       nan]
 [7.000e+00 5.000e+00 7.060e+02 ... 3.000e+00 5.480e+02 2.085e+05]
 [6.000e+00 8.000e+00 9.780e+02 ... 3.000e+00 4.600e+02 1.815e+05]
 ...
 [7.000e+00 6.000e+00 3.290e+02 ... 4.000e+00 2.400e+02 1.840e+05]
 [5.000e+00 7.000e+00 4.500e+02 ... 3.000e+00 2.880e+02 1.300e+05]
 [5.000e+00 7.000e+00 1.110e+02 ... 2.000e+00 2.970e+02 1.200e+05]]


ValueError: could not convert string to float: 'OverallQual,OverallCond,BsmtFinSF1,GrLivArea,BedroomAbvGr,GarageArea,SalePrice'